# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  jhi_starter-app:
    image: jhi_starter
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jhi_starter-postgresql:5432/jhi_starter
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://jhi_starter-postgresql:5432/jhi_starter
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:9000:9000
  jhi_starter-postgresql:
    image: postgres:14.5
    # volumes:
    #   - ~/volumes/jhipster/jhi_starter/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jhi_starter
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
